### ISSUE TITLE
tracking: Display

### ISSUE THREAD

**Issue by nazo6** [nazo6/rktk#23]
- [x] Basic OLED support
- [ ] Make display customizable
- [ ] Turn off OLED when inactive
