### ISSUE TITLE
tracking: Remapper(rrp)

### ISSUE THREAD

**Issue by nazo6** [nazo6/rktk#25]
- [ ] Implement remapper
   - [x] Basic remap feature
   - [ ] Tap-dance remap 
- [ ] Implement configuration manager 
- [x] Implement logger
- [ ] Improve logger performance (maybe migrate to hid from current usb serial)
